   name: Deploy Hugo to GitHub Pages

   on:
     push:
       branches:
         - main  # Change this to your default branch if it's not 'main'

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Setup Hugo
           uses: peaceiris/actions-hugo@v2
           with:
             hugo-version: 'latest'

         - name: Build
           run: hugo -D

         - name: Deploy
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ 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 }}  # Use the new secret here
             publish_dir: ./public